# Generated by Django 5.0.2 on 2024-04-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuarios',
        ),
    ]
