# Generated by Django 5.0.2 on 2024-04-25 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_user_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='age',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='dpi',
            field=models.CharField(default='null', max_length=13),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='correo@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tel',
            field=models.CharField(blank=True, default='null', max_length=8),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
